### ISSUE TITLE
viewer_->setThreadingModel( osgViewer::CompositeViewer::SingleThreaded ); required

### ISSUE THREAD

**Issue by fiesh** [Submanifold/QtOSG#1]
Alas is this quite bad, it makes the whole application only run on one core (under linux at least).  Is there a good way around this, allowing proper multithreading?

**Comment by Pseudomanifold** [comment]
To be honest, I am not sure. I was under the impression that multi-threaded rendering with Qt causes problems anyway, so I refrained from using it. Do you know whether the `QOpenGLWidget` is capable of handling multi-threaded rendering on its own?

**Comment by fiesh** [comment]
I think the differences between `QGLWidget` and `QOpenGLWidget` are quite small -- however, we can only use the former since we use remote rendering which is only supported in OpenGL < 2, which in turn is no longer supported in `QOpenGLWidget`.

The problem is not the rendering, I'd be fine with it being single thread.   But the whole application becomes single threaded, which is not acceptable.

**Comment by fiesh** [comment]
It appears there are people that have it in Qt, doing mutlithreading:http://forum.openscenegraph.org/viewtopic.php?t=13602

But maybe not entirely without problems: http://forum.openscenegraph.org/viewtopic.php?t=15772

**Comment by Pseudomanifold** [comment]
OK, I am starting to grasp the issue. For QtOSG, I have been using on-demand rendering anyway. Does this impact your performance&mdash;or do you require continuous rendering? If so, you may want to try setting the corresponding threading model in the constructor.

Does this work for you? I would expect it to result in a segmentation fault, though.

**Comment by fiesh** [comment]
I don't require continuous rendering, but changing the threading model in the ctor does not work :(  I'm beginning to wonder if this isn't rather an OSG bug, that the whole application then just runs on one core.

**Comment by fiesh** [comment]
OK, subclassing the CompositeViewer one can make the rest of the application not just run on one core as CompositeViewer normally forces you to.  So I guess it's not that big a deal if the rendering runs on a single core!

**Comment by Pseudomanifold** [comment]
OK, I am glad that this has been resolved for you. Would it make sense for you to contribute this change to `QtOSG`? Maybe others would be able to benefit from this.

**Comment by fiesh** [comment]
Sure, will do, good idea!
