### ISSUE TITLE
Is your way a preferred one that  embeds OSG into qt?

### ISSUE THREAD

**Issue by XIE-Yao** [Submanifold/QtOSG#12]
After all, there are osgQt module in OSG project and it works well, except nearly impossible to draw a rectangular in a picking process.   Your OSGWidget inherits QGLWidget straitforwardlly, is this a hacking way to use OSG in qt?

**Comment by Pseudomanifold** [comment]
When I wrote the widget, support for `osgQt` was not the best. I tried to make this a very light-weight widget that only encapsulates the core functionality, but I would not say that this is 'preferred way'; at least, it is not the preferred way of OpenSceneGraph.

Does that answer your question?

**Comment by XIE-Yao** [comment]
Your anwser is more than expected. Indeed it's very attractive that QtOSG extends QGLWidget directly, which brings much convinience(such as drawing rect on gl canvas directly instead of using HUD module). I have tried to modify osgQt module, trying to add some feature into it's GLWidget class (which extends QGLWidget), but fillaly failed.  

Pity that my skills on OSG is not that good, or I can contribute  some improvements on your project.

**Comment by Pseudomanifold** [comment]
Thanks for your kind words!

I'll close the issue for now and wish you the best of luck for your journey of learning. If you have any other questions or improvements, I will gladly add them :-)
