### ISSUE TITLE
Loading .shp file on osgEarth::MapNode

### ISSUE THREAD

**Issue by MrFatGG** [Submanifold/QtOSG#13]
When I load a SHP file on osgEarth:: MapNode and attach AltitudeSymbol clamping : CLAMP_TO_TERRAIN  to the SHP file, the Earth disappears

	Map* map = new Map();

	OGRFeatureOptions featureData;
	featureData.url() = "D:/src/osgearth-2.10/data/world.shp";

	FeatureSourceLayerOptions ogrLayer;
	ogrLayer.name() = "vector-data";
	ogrLayer.featureSource() = featureData;
	map->addLayer(new FeatureSourceLayer(ogrLayer));

	Style style;
	LineSymbol* ls = style.getOrCreateSymbol<LineSymbol>();
	ls->stroke()->color() = Color::Yellow;
	ls->stroke()->width() = 2.0f;
	ls->tessellationSize()->set(100, Units::KILOMETERS);
	AltitudeSymbol* alt = style.getOrCreate<AltitudeSymbol>();
	alt->clamping() = alt->CLAMP_TO_TERRAIN;
	alt->technique() = alt->TECHNIQUE_DRAPE;
	
	FeatureModelLayerOptions fml;
	fml.name() = "My Features";
	fml.featureSourceLayer() = "vector-data";
	fml.styles() = new StyleSheet();
	fml.styles()->addStyle(style);

	map->addLayer(new FeatureModelLayer(fml));

	MapNode* mapNode = new MapNode(map);

**Comment by Pseudomanifold** [comment]
This does not seem to be related to `QtOSG`. I am not affiliated with OpenSceneGraph in any way and I do not know anything about the `osgEarth` module. Please re-open this issue at the [official OSG issue tracker](https://github.com/openscenegraph/OpenSceneGraph/issues).

Let me know if that helps!
