### ISSUE TITLE
My app crashes when I want to add your OSGWidget to my GUI

### ISSUE THREAD

**Issue by seanrekrap** [Submanifold/QtOSG#14]
Hello - 

I'm new to Qt5/OSG... I'm trying to build an app using at least your design, if not your classes directly, just to take baby steps in integrating OSG and Qt together... This is on LUbuntu, with osg from a few months ago installed.
My application builds and starts fine (I see two red spheres like I do when I run your project OOTB)...but it crashes.... (I'm using valgrind):

Here's a very short snippet of valgrind output:

> ==3663== Memcheck, a memory error detector
> ==3663== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
> ==3663== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
> ==3663== Command: qt_user_test --log-file=/test/user/qt/qt_user_test.log --log-level=DEBUG --ui-config=test/user/qt/user-demo-ui.xml
> ==3663== 
> ==3663== Thread 2:
> ==3663== Invalid write of size 4
> ==3663==    at 0x10BDB070: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
> ==3663==    by 0x10BD7CA0: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
> ==3663==    by 0x10C7176B: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
> ==3663==    by 0xF59D0C7: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0)
> ==3663==    by 0xF59DF57: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0)
> ==3663==    by 0x40377A5: ??? (in /usr/local/Qt-5.8.0/plugins/xcbglintegrations/libqxcb-glx-integration.so)
> ==3663==    by 0x40358B6: ??? (in /usr/local/Qt-5.8.0/plugins/xcbglintegrations/libqxcb-glx-integration.so)
> ==3663==    by 0x409B990: QXcbIntegration::createPlatformOpenGLContext(QOpenGLContext*) const (in /usr/local/Qt-5.8.0/lib/libQt5XcbQpa.so.5.8.0)
> ==3663==  Address 0x7fb9bb2df000 is not stack'd, malloc'd or (recently) free'd
> ==3663== 
> ==3663== Invalid write of size 4
> ==3663==    at 0x10BDB077: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
> ==3663==    by 0x10BD7CA0: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
> ==3663==    by 0x10BD7E8E: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
> ==3663==    by 0xF59DF57: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0)
> ==3663==    by 0x40377A5: ??? (in /usr/local/Qt-5.8.0/plugins/xcbglintegrations/libqxcb-glx-integration.so)
> ==3663==    by 0x40358B6: ??? (in /usr/local/Qt-5.8.0/plugins/xcbglintegrations/libqxcb-glx-integration.so)
> ==3663==    by 0x409B990: QXcbIntegration::createPlatformOpenGLContext(QOpenGLContext*) const (in /usr/local/Qt-5.8.0/lib/libQt5XcbQpa.so.5.8.0)
> ==3663==  Address 0x7fb9bb2df004 is not stack'd, malloc'd or (recently) free'd
> ==3663== 
> ==3663== Invalid write of size 4
> ==3663==    at 0x10BDB1E4: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
> ==3663==    by 0x10C7176B: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
> ==3663==    by 0xF59D0C7: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0)
> ==3663==    by 0xF584D48: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0)
> ==3663==    by 0xF59DF57: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0)
> ==3663==    by 0x40377A5: ??? (in /usr/local/Qt-5.8.0/plugins/xcbglintegrations/libqxcb-glx-integration.so)
> ==3663==    by 0x40358B6: ??? (in /usr/local/Qt-5.8.0/plugins/xcbglintegrations/libqxcb-glx-integration.so)
> ==3663==    by 0x409B990: QXcbIntegration::createPlatformOpenGLContext(QOpenGLContext*) const (in /usr/local/Qt-5.8.0/lib/libQt5XcbQpa.so.5.8.0)
> ==3663==  Address 0x7fb9bb2df008 is not stack'd, malloc'd or (recently) free'd
> ==3663== 
> ....
<for thousands of lines...>

And here's where I'm instantiating you OSGWidget class (unmodified):

> void
> MainWindow::buildSplitScreen(bool horiz)
> {
>     QSplitter*   splitter = new QSplitter(centralWidget());
>     ...
>     if (!horiz)
>     {
>         splitter->setOrientation(Qt::Vertical);
>     }
>     splitter->setChildrenCollapsible(false);
>     
>    ...
>             OSGWidget* osgWidget = new OSGWidget( NULL);   //  I tried passing in splitter...      splitter );
>             splitter->addWidget(osgWidget);  
>    ...
> }

So, I'm just not sure where to start - since I'm using you CMakeLists and main as an example, etc...

Thanks for any suggestions you may have!

Cheers,
      Sean

**Comment by seanrekrap** [comment]
Oh... one detail that may matter... I'm instantiating the GUI in a thread NOT the main thread... this app works fine as long as I'm not instantiating OSGWidget... so Qt5 at least works fine with it starting up in non-main thread. I know the convention is to start Qt stuff in main thread...

**Comment by Pseudomanifold** [comment]
Dear Sean,

Thanks for reaching out! I must admit that I don't have the time to work on this at present. I seem to recall that there are some issues with threading—but I also have not followed Qt/OSG for a while now. If I recall correctly, OSG also offers its own widget now. Maybe this would be an alternative?

**Comment by seanrekrap** [comment]
Thanks so much for responding!
I'm looking into OSG's Qt example - but I have OSG 3.4 which uses Qt4
for it's example...  so I'm pending on getting later OSG to use Qt5
with - then I'll just use OSG's example rather than try to get QtOSG
to work with my application yet.

Thanks!
       Sean

**Comment by Pseudomanifold** [comment]
Good luck, hope it works :-)
