### ISSUE TITLE
Draw 2D graphics onto a QOpenGLWidget subclass using QPainter

### ISSUE THREAD

**Issue by ytyisme** [Submanifold/QtOSG#7]
This URL (http://doc.qt.io/qt-5/qopenglwidget.html)show Draw 2D graphics onto a QOpenGLWidget subclass using QPainter.I don't konw why you reimplement the paintEvent() and call makeCurrent() and doneCurrent().

Install Qt5.9.1 with examples, you will find one example qopenglwidget in Qt5.9.1\Examples\Qt-5.9.1\opengl\. qopenglwidget is a example show how to Draw 2D graphics onto a QOpenGLWidget subclass using QPainter.I tried to modify your code to make it look like that example. I remove paintEvent(),and put QPainter in paintGL(), but it not works.

You can try it.

**Comment by Pseudomanifold** [comment]
I am not sure what you mean in this issue. Do you want me to remove the `paintEvent` that I implemented in the widget? In my implementation, I need `paintEvent` in order to paint the selection rectangle with `QPainter`. Since the OSG widget displays a mixture of both 3D graphics (OpenSceneGraph) and 2D graphics (`QPainter`), I thought that this was the best solution. The Qt documentation states that this makes sense, as far as I understand.

**Comment by ytyisme** [comment]
Now, in the windows platform，can’t display the things **QPainter** draw when use your code. My English is poor. Most of them are from google translation

**Comment by Pseudomanifold** [comment]
I am sorry, I do not have much experience with programming for Microsoft Windows. I will try to look into this. Can you send me some screenshots maybe?

**Comment by ytyisme** [comment]
Now show the correct under Windows
I modified as follows
> class OSGWidget : public QOpenGLWidget,protected QOpenGLFunctions

` void OSGWidget::paintGL()`
`{`
`    glPushAttrib(GL_ALL_ATTRIB_BITS);`
`    glPushClientAttrib(GL_ALL_ATTRIB_BITS);`
`    viewer_->frame();`
`    glPopAttrib();`
`    glPopClientAttrib();`
`}`

Under Windows, you need to add the link library `opengl32.lib`

**Comment by Pseudomanifold** [comment]
Thank you for these modifications! Is the `protected QOpenGLFunctions` required?

**Comment by ytyisme** [comment]
If you do not inherit `QOpenGLFunctions` then the `OpenGL` function will not be declared. You may need to include the `gl.h` header file

**Comment by Pseudomanifold** [comment]
Thank you for the reply! I will refer to this discussion in the README file because, as I said, I do not have sufficient experience with programming for Microsoft Windows.

**Comment by qbingx** [comment]
Error D8021 invalid numeric argument '/Wno-long-long' qtosg	E:\OSG\QtOSG\build\cl	
I used the vs2015-64 platform + Qt5.6.1，the above error occurred.

i need your help，thx！
