### ISSUE TITLE
Please enable "make install"

### ISSUE THREAD

**Issue by probonopd** [Submanifold/QtOSG#9]
I would expect it to install the application into the system, along with a desktop file and icon. Please change your `.pro` file it similar to https://github.com/probonopd/FeedTheMonkey/blob/master/FeedTheMonkey.pro.

**Comment by Pseudomanifold** [comment]
This should be fixed in the master branch. I am not sure *why* you would want to install this demo application, though ;-) Would you kindly test whether this matches your expectations?

**Comment by probonopd** [comment]
Thank you very much, it does.
